# Generated by Django 2.2.1 on 2019-05-14 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190514_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 16, 19, 48, 177567), verbose_name='date published'),
        ),
    ]
