# Generated by Django 2.2.1 on 2019-05-14 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190514_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='writer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 16, 22, 26, 627950), verbose_name='date published'),
        ),
    ]
