# Generated by Django 2.2.1 on 2019-05-18 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190518_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 23, 34, 54, 611483), verbose_name='date published'),
        ),
    ]
