# Generated by Django 2.2.1 on 2019-05-18 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190518_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 23, 36, 36, 697513), verbose_name='date published'),
        ),
    ]
