# Generated by Django 2.2.1 on 2019-05-18 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190518_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com_writer',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 0, 12, 20, 679207), verbose_name='date published'),
        ),
    ]
