# Generated by Django 2.2.1 on 2019-05-28 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190519_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 18, 54, 47, 623989), verbose_name='date published'),
        ),
    ]
